trigger:
- none

pool:
  name: "agent5"

jobs:
- job: "terraform_workflow"
  displayName: "Terraform Workflow"
  steps:
  
  # Install a specific Terraform version
  - task: TerraformInstaller@1
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '1.5.6'   # Lock to a specific version for stability

  # Terraform init
  - task: TerraformTask@5
    displayName: "Terraform Init"
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'vinod_conn_new'
      backendAzureRmStorageAccountName: 'vinodstoragetest22'
      backendAzureRmContainerName: 'container1'
      backendAzureRmKey: 'st.terraform.tfstate'
      ensureBackend: true

  # Terraform validate
  - task: TerraformTask@5
    displayName: "Terraform Validate"
    inputs:
      provider: 'azurerm'
      command: 'validate'

  # Terraform plan
  - task: TerraformTask@5
    displayName: "Terraform Plan"
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'vinod_conn_new'

  # Terraform apply
  - task: TerraformTask@5
    displayName: "Terraform Apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'vinod_conn_new'
