trigger:
- main

pool:  agent5

steps:
- task:
  displayName: "terrafom latest"
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  
- task:
  displayName: "terrform init"
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'

- task:
  displayName: "terrform plan"
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'

- task:
  displayName: "terrform apply"
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve'