trigger:
- main

pool:  agent5

steps:
  - task: TerraformInstaller@1
    displayName: "terrafom latest"
    inputs:
      terraformVersion: 'latest'
  
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'vinod_conn_new'
      backendAzureRmStorageAccountName: 'vinodstoragetest22'
      backendAzureRmContainerName: 'container1'
      backendAzureRmKey: 'st.terraform.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'vinod_conn_new'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: 'vinod_conn_new'